//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sameera_Pizza.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetData", ReplyAction="http://tempuri.org/IService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetData", ReplyAction="http://tempuri.org/IService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SetData", ReplyAction="http://tempuri.org/IService/SetDataResponse")]
        string SetData(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SetData", ReplyAction="http://tempuri.org/IService/SetDataResponse")]
        System.Threading.Tasks.Task<string> SetDataAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/item1", ReplyAction="http://tempuri.org/IService/item1Response")]
        string[] item1();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/item1", ReplyAction="http://tempuri.org/IService/item1Response")]
        System.Threading.Tasks.Task<string[]> item1Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/itemName", ReplyAction="http://tempuri.org/IService/itemNameResponse")]
        string[] itemName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/itemName", ReplyAction="http://tempuri.org/IService/itemNameResponse")]
        System.Threading.Tasks.Task<string[]> itemNameAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Sameera_Pizza.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Sameera_Pizza.ServiceReference1.IService>, Sameera_Pizza.ServiceReference1.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public string SetData(string username, string password) {
            return base.Channel.SetData(username, password);
        }
        
        public System.Threading.Tasks.Task<string> SetDataAsync(string username, string password) {
            return base.Channel.SetDataAsync(username, password);
        }
        
        public string[] item1() {
            return base.Channel.item1();
        }
        
        public System.Threading.Tasks.Task<string[]> item1Async() {
            return base.Channel.item1Async();
        }
        
        public string[] itemName() {
            return base.Channel.itemName();
        }
        
        public System.Threading.Tasks.Task<string[]> itemNameAsync() {
            return base.Channel.itemNameAsync();
        }
    }
}
